### ISSUE TITLE
Compiling the DSL

### ISSUE THREAD

**Issue by rob005** [liquibase/liquibase-groovy-dsl#11]
Ok, so I'm new to this game :(

I have downloaded the ZIP and I don't see any classes, so I am guessing I have to build/compile this using gradle?
#### > gradle -v

---
## Gradle 2.10

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.6.0_45 (Sun Microsystems Inc. 20.45-b01)
OS:           Windows 7 6.1 amd64
#### > gradle (?)

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring root project 'liquibase-groovy-dsl-master'.
- Could not resolve all dependencies for configuration ':classpath'.
  - Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:0.6.
    Required by:
       :liquibase-groovy-dsl-master:unspecified
    - Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:0.6.
      - Could not get resource 'https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/0.6/gradle-bintray-plugin-0.6.pom'.
        - Could not GET 'https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/0.6/gradle-bintray-plugin-0.6.pom'.
          - peer not authenticated
    - Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:0.6.
      - Could not get resource 'https://repo1.maven.org/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/0.6/gradle-bintray-plugin-0.6.pom'.
        - Could not GET 'https://repo1.maven.org/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/0.6/gradle-bintray-plugin-0.6.pom'.
          - peer not authenticated

If I put the URL in a browser, I get a 404

On the basis that it seems I have a certificate issue, I downloaded the jfrog JAR (https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/0.6/) and altered the build.gradle:

```
dependencies {
  files('../libs/gradle-bintray-plugin-0.6.jar')
```
#### >gradle

FAILURE: Build failed with an exception.
- Where:
  Build file 'D:\tidev\tools\liquibase-3.4.2\liquibase-groovy-dsl-master\build.gradle' line: 19

What went wrong:
A problem occurred evaluating root project 'liquibase-groovy-dsl-master'.
- Plugin with id 'com.jfrog.bintray' not found.
## Any clues?

I do not use Maven, so all I am after is (I guess) a build that creates a JAR or I need to JAR the classes built.

We will be using _liquibase_ from the command line, rather than via gradle or gradlew.
This assumes we have the DSL in a jar such as `liquibase-groovy.jar` in the current directory.

> liquibase --changeLogFile=a.groovy update

Any help gratefully received.

**Comment by stevesaliman** [comment]
You have 2 options for getting the DSL jar:

1) Clone this project, and execute `gradlew install`.  This will put the jar in the `build/libs` directory of the project.

2) Download the jar from [Maven Central](https://search.maven.org/remotecontent?filepath=org/liquibase/liquibase-groovy-dsl/1.2.1/liquibase-groovy-dsl-1.2.1.jar).  Once you have the jar, you'll need to use Liquibase's `--classpath` option to include it.

**Comment by rob005** [comment]
I chose option 2)  and placed the JAR into the lib directory

#### lib

20/01/2016  15:24           151,671 liquibase-groovy-dsl-1.2.1.jar
15/10/2015  13:38           960,374 mysql-connector-java-5.1.34-bin.jar
24/10/2014  19:12           273,449 snakeyaml-1.13.jar

I have a changelog file, _a.xml_ that has an include to a file _a.groovy_

#### Running the app

java -cp ".;d:\tidev\tools\liquibase-3.4.2_X\liquibase.jar;d:\tidev\tools\liquibase-3.4.2_X\lib\liquibase-groovy-dsl-1.2.1.jar;d:\tidev\tools\liquibase-3.4.2_X\lib\liquibase-groovy-dsl-1.2.1.jar;d:\tidev\tools\liquibase-3.4.2_X\lib\mysql-connector-java-5.1.34-bin.jar;d:\tidev\tools\liquibase-3.4.2_X\lib\snakeyaml-1.13.jar"  liquibase.integration.commandline.Main --logLevel warning --changeLogFile a.xml updatesql 

This gives me a warning...

WARNING 20/01/16 15:59: liquibase: included file a.xml/a.groovy is not a recognized file type

**Comment by stevesaliman** [comment]
It looks like you are trying to mix XML and Groovy.  I'm not sure what happens when you try to do that.

I think your best bet is to either be all XML or all Groovy.  It will certainly cause less confusion to developers who come later and need to support the code.

**Comment by rob005** [comment]
This fails even if I just run with a `changeLogFile=a.groovy`

`liquibase --changeLogFile=a.groovy --classpath=lib\liquibase-groovy-dsl-1.2.1.jar updateSQL`
`Unexpected error running Liquibase: Cannot find parser that supports a.groovy`

or

`liquibase --changeLogFile=a.groovy updateSQL`
`Unexpected error running Liquibase: Cannot find parser that supports a.groovy`

**Comment by vporoxnenko** [comment]
> > stevesaliman commented 3 days ago
> > It looks like you are trying to mix XML and Groovy. I'm not sure what happens when you try to do that.

mixing works well, because liquibase call own interpreter per each file, so xml will be processed by xml processor and groovy by groovy

> > Unexpected error running Liquibase: Cannot find parser that supports a.groovy
> > liquibase-groovy-dsl-1.2.1.jar is in yours classpath, but not groovy. I have groovy-all + liquibase-groovy-dsl + db driver + snakeyaml libs in my class path

without groovy-all yours dsl jar file just a zip archive of resources in classpath. JVM ignoring them

**Comment by rob005** [comment]
Many thanks vporoxnenko - that has saved the day

**Comment by vporoxnenko** [comment]
ok, send me a bottle of beer next time))

**Comment by rob005** [comment]
Why isn't this is the documentation???   But yes, :beer: :beer: :beer: :beer: :beer: for you

**Comment by vporoxnenko** [comment]
any groovy code, executed in jvm require to have groovy-all (but I resolved this problem when debugging :D )

**Comment by stevesaliman** [comment]
I'll add the groovy-all dependency to the DSL documentation.  Thank you for your help vporoxnenko. 

I wasn't sure what would happen when you mix file types because I hadn't thought to try it yet. :-)  It is good to know that Liquibase will do the right thing.
