### ISSUE TITLE
Missing groovy support for some XML equivalents

### ISSUE THREAD

**Issue by rob005** [liquibase/liquibase-groovy-dsl#12]
I've been fiddling with some groovy code to see what is/isn't supported in comparison to XML change sets. Mostly it is OK, but for some commands, I get, for example,  

```
''Unexpected error running Liquibase: ChangeSet 'test-mergeColumns': 'mergeColumns' is not a valid element of a ChangeSet''
```

My code (failures only) is

``` groovy
databaseChangeLog() {

def varTableName="testA"
def varAuthor="ra"

changeSet( author: varAuthor, id: "test-mergeColumns"){
        mergeColumns( tableName="testA", 
                 column1Name:"col3", joinString:":", column2Name:"col4",            finalColumnName:"MERGEDCOL", finalColumnType:"VARCHAR(20)")
}

changeSet( author: varAuthor, id: "test-addNotNullConstraint"){
        addNotNullConstraint( tableName:varTableName, columnName:"col2", columnDataType="CHAR")
}

changeSet( author: varAuthor, id: "test-renameColumn"){
        renameColumn(tableName: varTableName, oldColumnName: "col4", newColumnName:"FACTOR", columnDataType="INT")
}

changeSet( author: varAuthor, id: "test-addColumn"){
        addColumn(tableName: varTableName, type:"timestamp")
}

changeSet( author: varAuthor, id: "test-executeCommand", failOnError: false){
            executableCommand() {
                executable("something.groovy") {
                    arg "--x"
                    arg "--y:1" 
        }
}

changeSet( author: varAuthor, id: "test-loadData"){
        loadData(tableName: "testA", path:"test.csv")
}

changeSet( author: varAuthor, id: "test-loadUpdateData"){
        loadUpdateData(tableName: "testA", primaryKey: "col1", path:"test.csv")
}

}

```

Any comments gratefully received?

**Comment by stevesaliman** [comment]
The first thing that comes to mind is the use of the `=` in your changes.  `tableName='testA'` should be `tableName: 'testA'`.

The `executableCommand` change should be `executeCommand`.  

I'm not sure what is happening with the others.  Is "timestamp"  a valid column type for your database?  Do the files being loaded in your `loadData` and `loadUpdateData` exist in the given location?

The unit tests are actually a pretty good place to find Groovy examples of the various changes.  Each supported change has a test that sets all possible values to make sure they get passed on to Liquibase properly.  The bits you'd be interested is inside calls to `buildChangeSet`, which use the same code you'd have in your changeset file.
