### ISSUE TITLE
includeAll in changeLog throwing FileNotFoundException

### ISSUE THREAD

**Issue by mikeyudin** [liquibase/liquibase-groovy-dsl#13]
Hello,

I'm having a tough time getting my includeAll working properly.  When the `includeAll` method in the `DatabaseChangeLogDelegate` class attempts to locate files based on params.path, it's using an absolute path, not the classpath, so it throws exceptions like such:

`java.io.FileNotFoundException: C:\java\persons\classpath:\db\versions`

``` groovy
// This is using the absolute path
new File(params.path).eachFileMatch(~/.*.groovy/) { file ->
    if (resourceFilter == null || resourceFilter.include(file.path)) {
        files << file.path
    }
}
```

I have tried just about every combination of my primary changelog (below), but no matter what, I still get exceptions.

``` groovy
// classpath:/db/changeLog-master.groovy:

// doesn't work
databaseChangeLog {
    includeAll(path : "versions", relativeToChangelogFile: true)
}

// doesn't work
databaseChangeLog {
    includeAll(path : "classpath:/db/versions")
}

// this gets past the initial File matcher, but then fails when trying to locate the folder when the 
// parser starts actually searching the classpath
databaseChangeLog {
    includeAll(path : "src/main/resources/db/versions")
}
```

Attempting to fork the code and set the File matcher to use the classpath instead of absolute paths fails all of the tests, since the tests are testing the parserFactory, and not the File matcher.

Am I not configuring this properly, or is this an actual bug?

Thanks in advance for any assistance!

**Comment by stevesaliman** [comment]
I've never tried to use the classpath in my changelogs, since I've always got the working directory available when I run Liquibase from the command line.  In my case I use the gradle plugin.  My changelog contains only

``` groovy
databaseChangeLog {
  includeAll(path: "src/main/db/changelogs")
}
```

Which finds all my changelog files just fine when I do a build from the main project directory. I noticed that you have your changelogs in src/main/resources, which is typically included inside another application.  How are you running Liquibase?

**Comment by mikeyudin** [comment]
Attempting to run migrations via Spring Boot, when the context initializes. It seems to work fine if I use a yaml file to do my includeAll (even if the files in the includeAll path are groovy), as follows:

``` yaml
# src/main/resources/db/db.changelog-master.yaml
databaseChangeLog:
  - includeAll:
      path: versions
      relativeToChangelogFile: true
```

Yaml is the default format for Spring Liquibase integration, as described here:  https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-liquibase-database-migrations-on-startup

Seems like there may be a conflict in the way Spring boot passes the path to this library when specifying a groovy root changelog?

**Comment by stevesaliman** [comment]
The includeAll tag is one of the few things that isn't a simple pass-through to the Liquibase core code.  

I'll need to see if there is either a way to get the Groovy code to handle including files from a classpath, or pass a filtering mechanism to the Liquibase core that would just select the Groovy files - without preventing users from providing their own filter.  If I get some time this weekend, I'll look into it some more.

**Comment by stevesaliman** [comment]
I changed the way the Groovy DSL handles the includeAll tag and uploaded release 1.2.2-SNAPSHOT to the Maven snapshot repository.  

Can you give it a try and let me know how it works?  You should be able to use the following changelog:

``` groovy
databaseChangeLog {
    includeAll(path : "versions", relativeToChangelogFile: true)
}
```

**Comment by stevesaliman** [comment]
Release 1.2.2 is out with a fix for this issue.

**Comment by stevesaliman** [comment]
If you use the DSL via the Liquibase Gradle plugin, the 1.2.2 release of that plugin has a bug and should not be used.  Gradle users should use version 1.2.3 of the Gradle plugin.
