### ISSUE TITLE
include xml changelogs is impossible

### ISSUE THREAD

**Issue by vporoxnenko** [liquibase/liquibase-groovy-dsl#14]
it's currently impossible to include xml changelog files due to in-code restrictions

databaseChangeLog() {
  include(file: 'sequences.changelog.xml', relative: true)
  include(file: 'tables.changelog.xml', relative: true)
  ......
}

liquibase.exception.SetupException: DatabaseChangeLog:  'relative' is not a supported attribute of the 'include' element

it's required to use includeAll method instead, but this method includes only groovy file, and I need xml in my project

**Comment by stevesaliman** [comment]
I think that xml files might actually work, since Liquibase natively knows how to deal with XML files.

The problem here is probably that your change is using `relative` instead of `relativeToChangelogFile`...

**Comment by vporoxnenko** [comment]
I'm calling xml from groovy dsl, so it goes via groovy wrapper

see
org.liquibase.groovy.delegate.LegacyDatabaseChangeLogDelegate

void include(Map params = [:]) {
      if ( params.containsKey('path') ) {
          throw new ChangeLogParseException("Error: the 'include' element
no longer supports the 'path' attribute.  Please use the 'includeAll'
element instead.")
      }

```
  // validate parameters.
  def unsupportedKeys = params.keySet() - ['file',
```

'relativeToChangelogFile']
      if ( unsupportedKeys.size() > 0 ) {
          throw new ChangeLogParseException("DatabaseChangeLog:
'${unsupportedKeys.toArray()[0]}' is not a supported attribute of the
'include' element.")
      }....

it throw errors, but why?

2016-02-11 5:05 GMT+03:00 Steven C. Saliman notifications@github.com:

> I think that xml files might actually work, since Liquibase natively knows
> how to deal with XML files.
> 
> The problem here is probably that your change is using relative instead
> of relativeToChangelogFile...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/liquibase/liquibase-groovy-dsl/issues/14#issuecomment-182672305
> .

## 

Regards,
Valentin A. Poroxnenko

**Comment by stevesaliman** [comment]
`path` is not supported by the `include` change, but `file` is.  What happens if your changelog looks like this:

``` groovy
databaseChangeLog() {
  include(file: 'sequences.changelog.xml', relativeToChangelogFile: true)
  include(file: 'tables.changelog.xml', relativeToChangelogFile: true)
......
}
```

**Comment by vporoxnenko** [comment]
it's work
seems the problem was caused by stupid cut and paste

**Comment by stevesaliman** [comment]
I like to call that "edit time inheritance" :-)

Glad it's working for you now.

**Comment by vporoxnenko** [comment]
thanks

2016-02-15 18:02 GMT+03:00 Steven C. Saliman notifications@github.com:

> I like to call that "edit time inheritance" :-)
> 
> Glad it's working for you now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/liquibase/liquibase-groovy-dsl/issues/14#issuecomment-184243443
> .

## 

Regards,
Valentin A. Poroxnenko
