### ISSUE TITLE
'createIndex' is not a valid element of a ChangeSet

### ISSUE THREAD

**Issue by thorntonrose** [liquibase/liquibase-groovy-dsl#21]
When running update with a Groovy file generated by generateChangeLog, I get this error:

Execution failed for task ':update'.

> liquibase.exception.LiquibaseException: Unexpected error running Liquibase: ChangeSet '1470069484023-159': 'createIndex' is not a valid element of a ChangeSet

**Comment by stevesaliman** [comment]
I'm going to guess from this question that you figured out the answer to #20 :-)

I'm not sure why you are getting this error.  I just tried generating a changelog against one of my other projects, and it created changelogs with createIndex elements in them.  I than ran dropAll update, and it ran correctly on my system against a MySQL database. What exactly does changeSet 1470069484023-159 look like?

**Comment by bruce-one** [comment]
I encountered this error message because I had the wrong syntax in my changelog:

I had:

```
createIndex(tableName: 'table', columnNames: 'c1, c2', indexName: 'i_name', unique: 'true')
```

Whereas it should have been:

```
createIndex(tableName: 'table', indexName: 'i_name', unique: 'true') {
  column(name: 'c1')
  column(name: 'c2')
}
```

(I'd just converted `addUniqueConstraint` blindly, hence why I encountered the issue.)

(Just in case anyone else comes across this.)
