### ISSUE TITLE
Support sqlFile inside rollback

### ISSUE THREAD

**Issue by juancoen** [liquibase/liquibase-groovy-dsl#24]
```
rollback() {
  sqlFile(path: "rollback.sql", relativeToChangelogFile: true)
}
```

fails because "rollback.sql" is not found.
It seems that this combination is not supported by the dsl.

Thanks!

**Comment by trazy** [comment]
me too.. i try to in groovy file, new File({file path}).getAbsolutePath(), but java could not found file..

example > sqlFile(path: new File("rollback.sql").getAbsolutePath())

**Comment by stevesaliman** [comment]
I think I found the issue.  I'm working on a fix now, which I hope to have out in a few days.

**Comment by stevesaliman** [comment]
Release 1.2.2 is out with a fix for this issue.

**Comment by stevesaliman** [comment]
If you use the DSL via the Liquibase Gradle plugin, the 1.2.2 release of that plugin has a bug and should not be used. Gradle users should use version 1.2.3 of the Gradle plugin.
