### ISSUE TITLE
provide a autocompletion gdsl

### ISSUE THREAD

**Issue by dgeissl** [liquibase/liquibase-groovy-dsl#27]
I've seen this first used by [Jenkins](https://github.com/jenkinsci/job-dsl-plugin/wiki/IDE-Support) but that may close some gap between the xmls schema based autocompletion and groovy dsl readability.

https://confluence.jetbrains.com/display/GRVY/Scripting+IDE+for+DSL+awareness

**Comment by stevesaliman** [comment]
This looks a lot like #4.  And like #4, it is unlikely I'll get time to implement or maintain a solution.
