### ISSUE TITLE
Create and drop procedure improvements.

### ISSUE THREAD

**Issue by carlos-hernandez** [liquibase/liquibase-groovy-dsl#3]
Since the 1.0.2 version of the plugin I detected that the **createProcedure** changeset had problems finding the files that contains the SQL script with the code of the procedure.

Also, the **dropProcedure** changeset is not available in the actual DSL.

See the pull requests for more details.

**Comment by stevesaliman** [comment]
The pull requests mentioned fix this problem, so I'm closing the issue.
