### ISSUE TITLE
Use triple-quoted strings in serializer

### ISSUE THREAD

**Issue by ethanmdavidson** [liquibase/liquibase-groovy-dsl#39]
When running the generateChangeLog command on an oracle database, I run into a couple of issues:
1) objects with multiple lines, e.g. 
```groovy
  changeSet(id: '1551192953968-7', author: 'edavidson (generated)') {
    createView(fullDefinition: true, viewName: 'FR_TEXT_COUNT') {
      "CREATE OR REPLACE FORCE VIEW FR_TEXT_COUNT (APPID, ITEMID, TYPE, PANEL, COUNT) AS select appid,itemid,type,panel,count(1) from fr_text_long
      group by appid,itemid,type,panel"
    }
  }
```
2) objects with double quotes, e.g. 
 ```groovy
changeSet(id: '1551192755372-1043', author: 'edavidson (generated)') {
    createView(fullDefinition: true, viewName: 'HOLSCHED') {
      "CREATE OR REPLACE FORCE VIEW HOLSCHED (PERNO, DAYNO, HOLDATE, DESCR) AS SELECT "PERNO","DAYNO","HOLDATE","DESCR" FROM PAYROLL.HOLSCHED"
    }
  }
```

It seems to me that we could solve both these problems by using triple-quoted strings when writing [text bodies in the serializer](https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/main/groovy/liquibase/serializer/ext/GroovyChangeLogSerializer.groovy#L283), e.g: 
```groovy
serializedChange = """\
${serializedChange} {
  '''${textBody}'''
}"""
```

triple-single quotes would be easier here, but could still fail because oracle escapes single-quotes by using two (''), so when a string begins or ends with an escaped single-quote:
```sql
select 'the last char in this string is a single quote: ''' from dual;
```
the changelog generation would fail. A more robust solution would be to properly escape the text based on the sql dialect, but that's probably more trouble than it's worth. Triple-quoted strings should catch most cases, and it's easy enough to fix the generated changelog manually in the few cases that are missed.

Let me know your thoughts.

**Comment by ethanmdavidson** [comment]
Might also want to use them on [propertyString](https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/main/groovy/liquibase/serializer/ext/GroovyChangeLogSerializer.groovy#L325) as well, because some properties can have multiple line values:

```groovy
changeSet(id: '1551192755372-32', author: 'edavidson (generated)') {
    createTable(remarks: 'This is a very long comment:
    heres the second line
    and heres another line', tableName: 'PAYMENT_PROC_DETAIL') {
 ```

**Comment by stevesaliman** [comment]
Version 2.0.3 of the Groovy DSL has been released with a fix for this issue.
