### ISSUE TITLE
Context for being able to use autocomplete of the dsl in different IDEs

### ISSUE THREAD

**Issue by luislarrateguy** [liquibase/liquibase-groovy-dsl#4]
I'm trying to use the DSL since it's opens up the posibilites more than using XML. For the XML we had the XSD which allows you to type faster (although still XML) the changelogs/changesets. In this DSL I'd like to do the same, but I couldn't set a context around the IDE so it knows what to suggest.

I'm reporting this not as a bug but as improvement.

**Comment by ryan-gustafson** [comment]
For Eclipse, if you're using the Groovy Eclipse plugin, this is what you need to write:  https://github.com/groovy/groovy-eclipse/wiki/DSLD-examples

I explored what it would take to do this, to facilitate switching from XML to Groovy DSL, as the IDE completion is extremely useful for discovery.  I stopped when I realized I'd probably need to parse/interpret the XML XSD, which for Liquibase is a non-trivial schema.  If you could extract the metadata for all the XML elements/attributes along with the element nesting, it should be possible to drive creation of the needed DSLD pointcuts.  I had it mostly working for some hand-written element metadata.

**Comment by stevesaliman** [comment]
The biggest challenge with doing something like this is keeping up with the changing DSL as Liquibase itself changes.  Also, extensions can add properties to change sets as well.  My goal with the DSL is to use it as a pass through to Liquibase and not have to change it whenever a new release of Liquibase comes along.

Chances are, if I haven't had time to look into this up to now, I probably never will.  I'm going to close this as a "won't fix" issue.  Sorry for the inconvenience.
