### ISSUE TITLE
Some unit tests always fail on windows

### ISSUE THREAD

**Issue by ethanmdavidson** [liquibase/liquibase-groovy-dsl#40]
Some of the tests rely on absolute paths to changelog files. However, in order to verify that a path is absolute, they rely on assertions like 
```groovy
assertTrue includedChangeLogFile.startsWith("/")
```
which fails on windows, where the path will start with the drive name, e.g. 'C:/'. 

Instead of working with strings, these tests should take advantage of  [java.io.File](https://docs.oracle.com/javase/8/docs/api/java/io/File.html) in order to work correctly across systems.

Tests which are affected by this:
[org.liquibase.groovy.delegate.DatabaseChangeLogDelegateIncludeTests](https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/test/groovy/org/liquibase/groovy/delegate/DatabaseChangeLogDelegateIncludeAllTests.groovy)
[org.liquibase.groovy.delegate.DatabaseChangeLogDelegateIncludeTests](https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/test/groovy/org/liquibase/groovy/delegate/DatabaseChangeLogDelegateIncludeTests.groovy)

**Comment by stevesaliman** [comment]
Version 2.0.3 of the Groovy DSL has been released with a fix for this issue.
