### ISSUE TITLE
deleteCascade typo?

### ISSUE THREAD

**Issue by beatyt** [liquibase/liquibase-groovy-dsl#43]
`'deleteCascase' is not a valid constraint attribute for 'addColumn' changes.`

https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/test/changelog/changelog.groovy#L100

https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/test/changelog/changelog.groovy#L247

**Comment by stevesaliman** [comment]
Good catch.  Those are indeed typos, which I've now fixed.

Thanks for finding them.
