### ISSUE TITLE
How to add onDelete: Cascade to a foreign key constraint?

### ISSUE THREAD

**Issue by rolf-rosenbaum** [liquibase/liquibase-groovy-dsl#44]
the liquibase doc mentions the possibilty to create foregin key constraints with a param 'onDelete'
https://www.liquibase.org/documentation/changes/add_foreign_key_constraint.html

How would I do this with the groovy dsl?

**Comment by stevesaliman** [comment]
You should be able to do something like this inside a change set:
```
addForeignKeyConstraint(
		constraintName: 'fk_my_key',
		baseTableName: 'my_table',
		baseColumnNames: 'foreign_id',
		referencedTableName: 'foreign_table',
		referencedColumnNames: 'id',
		deferrable: true,
		initiallyDeferred: false,
		onDelete: 'RESTRICT',
		onUpdate: 'CASCADE',
)
```
