### ISSUE TITLE
changeSet logicalFilePath not recognized

### ISSUE THREAD

**Issue by stanio** [liquibase/liquibase-groovy-dsl#45]
There's a `logicalFilePath` attribute to `changeSet` elements (see the `changeSetAttributes` attribute group):

http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd

It appears to map to [`ChangeSet.filePath`](https://github.com/liquibase/liquibase/blob/3.8.x/liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java) property.  Neither of `logicalFilePath` or `filePath` appears recognized by the Groovy DSL:

```groovy
    changeSet(id: '1', author: 'saly', logicalFilePath: 'c1') {
        // ...
    }
    changeSet(id: '2', author: 'holy', logicalFilePath: 'c2') {
        // ...
    }
```

I'm trying this in the context of [CORE-3549](https://liquibase.jira.com/browse/CORE-3549) where  I'm trying to convert any change log source to XML for use in runtime package without extra dependencies.

I'm also evaluating the conversion of Liquibase XML to Groovy DSL (for being more readable source) using [XSLT](https://gist.github.com/stanio/4b4b6f57bae0df4bf166909f37bc2a4b).  In all cases, I need to preserve/set the `logicalFilePath` to `datachangeLog`s and individual `changeSet`s, the latter of which doesn't appear supported in the Groovy DSL, currently.

**Comment by stevesaliman** [comment]
Release 2.1.1 of the Groovy DSL adds support for this missing (and undocumented) attribute.  The XML supports `logicalFilePath`, the Java property is called `filePath`.  The Groovy DSL supports both.

This release should show up in the normal mirrors in the next couple of hours.

**Comment by stanio** [comment]
Thank you for the quick fix!
