### ISSUE TITLE
Update Groovy dependencies 

### ISSUE THREAD

**Issue by Godsim** [liquibase/liquibase-groovy-dsl#46]
The current dependencies org.codehaus.groovy:groovy and groovy-dsl are not compatible with OpenJDK 14 and break Spring Boot application execution at startup with:

java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>
...

and

java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
	at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33) ~[groovy-2.5.8.jar:2.5.8]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
...

Replacing the dependencies manually with groovy:3.0.3 and groovy-dsl:3.0.3
seems to work without issues.

**Comment by stevesaliman** [comment]
I tried updating the dependencies in the Gradle plugin, but what I noticed is that when I tested it in a project that was using Spring, the groovy dependencies were being pulled down to a version Spring was happy with.  That, and the fact that Gradle itself is still using a 2.x version of Groovy, plus the fact that I think a LOT of people are still using Java 11 and even Java 8, make me reluctant to incorporate this change at this time.

For people who need a newer version of Groovy for Java 14 projects, you can probably add the following dependencies to your project to have the Liquibase Groovy DSL use Groovy 3:
```groovy
  liquibaseRuntime 'org.codehaus.groovy:groovy:3.0.3'
  liquibaseRuntime 'org.codehaus.groovy:groovy-sql:3.0.3'
```

**Comment by stevesaliman** [comment]
Since this issue was opened, most people have moved to Gradle 7.x, which uses Groovy 3.x.  I've bumped the transitive dependency on Groovy to 3.0.15, and added support for 4.x, though that requires a slightly more complicated way to manually specify the dependency, as shown in the README.md doc.
