### ISSUE TITLE
README.md references Version 3.0.1, 3.0.0 is latest published release

### ISSUE THREAD

**Issue by jshickey** [liquibase/liquibase-groovy-dsl#49]
Can't find a 3.0.1 published anywhere.

https://mvnrepository.com/artifact/org.liquibase/liquibase-groovy-dsl

**Comment by stevesaliman** [comment]
Thank you for catching this.  It looks like I prepared the release, but forgot to actually release it.  

I just released version 3.0.1 with support for Liquibase 4.3.3, it should show up on Maven Central shortly.
