### ISSUE TITLE
Incompatible with liquibase v4.17.0 due to breaking change

### ISSUE THREAD

**Issue by erichelgeson** [liquibase/liquibase-groovy-dsl#54]
[liquibase v4.17.0](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) removed [FileSystemResourceAccessor](https://github.com/liquibase/liquibase/pull/3064) which is still in use here https://github.com/liquibase/liquibase-groovy-dsl/blob/master/src/main/groovy/org/liquibase/groovy/delegate/DatabaseChangeLogDelegate.groovy#L36

This causes a runtime class not found exception for `FileSystemResourceAccessor`.

**Comment by stevesaliman** [comment]
This is going to be a big change if we are going to be able to maintain backwards compatibility.  I'm going to have to figure out some way to use the right class for the version of Liquibase in the runtime classpath, and I'll need to figure out how this impacts the things that rely on the resource accessor, like `include` and `includeAll.

This will likely take me some time to figure out.

**Comment by filipelautert** [comment]
Hello @erichelgeson - it was restored on 4.18.0 here -> https://github.com/liquibase/liquibase/pull/3499 .
