### ISSUE TITLE
Official 3.0.3 release tag missing

### ISSUE THREAD

**Issue by yuri1969** [liquibase/liquibase-groovy-dsl#56]
The 3.0.3 has been been [available for a while](https://mvnrepository.com/artifact/org.liquibase/liquibase-groovy-dsl/3.0.3). Is there a reason not to release it via a [standard tag](https://github.com/liquibase/liquibase-groovy-dsl/tags)?

**Comment by stevesaliman** [comment]
The reason is that I totally forgot :-)  

The tag is there now.  Thanks for letting me know.
