### ISSUE TITLE
use groovy class, declared in groovy changelog

### ISSUE THREAD

**Issue by vporoxnenko** [liquibase/liquibase-groovy-dsl#8]
currently next changeset would give an ClassNotFound exception

import blablabla.....

public class TaskChange implements CustomTaskChange {

```
private String param1;
    public String getParam1() {
      return param1;
    }

    public void setParam1(String file) {
       this.param1 = file;
     }
@Override
public void execute(Database db) throws CustomChangeException {
          doCoolStuff(db);
}

   .........other methods
```

}

databaseChangeLog() {

  changeSet(author: 'dude', id: 'test-1') {

```
  customChange(class: 'TaskChange') {
    param(name: 'param1', value: 'absolutely new value')
}
```

  }

}

it happens because ChangeSetDelegate pass liquibase classloader, but not groovy shell classloader

so class TaskChange wouldn't never be found, or I should take care to load my internal class into the parent classloader, which doesn't look nice

**Comment by stevesaliman** [comment]
Version 1.2.1, with Pull Request #6 has been published.
